const startGifs = [
    'CgACAgQAAxkBAAIBw2cp6gx4r-byjbNcO78cvmK0V6nNAAJaBQAChOo9UBKYw5-iru7fNgQ',
    'CgACAgQAAxkBAAIBwmcp6fgjmzCQIRKUkZob1EuJUnkqAALYAgAC8Q8cU-zG5tTdXcoYNgQ',
    'CgACAgQAAxkBAAIBwWcp6XAp16R2zzHsueO-c9lfP49sAAICAwACzAScUSF9uAXhc1PuNgQ',
    'CgACAgQAAxkBAAIcE2gWUoYs3ToQiEsYUalwzQhWVAQIAALhAgAC3WAMU-lTBurTtNEUNgQ',
    'CgACAgQAAxkBAAIcFmgWU0PUpRbewhHqUfQ6ZqSsMdVYAAIuAwACxPEFUwdCGeYxdWPENgQ',
    'CgACAgQAAxkBAAIcF2gWU3zIb4cox2ieUYszWkMXdaqIAAJ4AwACXpa9UOFuO2ihBUJyNgQ',
    'CgACAgQAAxkBAAIcGGgWU9pn9TBLZoIxt6sIameV_GbfAALtAgAC0t0tU1Fb1y1tRi_fNgQ',
    'CgACAgQAAxkBAAIcGWgWVOEy-JV1CDOhoIE4rqH2HEiCAAJ9BwACCErtUBEi0yu8f7ggNgQ',
];

const cancelGifs = [
    'CgACAgQAAxkBAAICSWcrsZ3CvH3b6C4LxtXjpfzCijtZAALkAgACce8lU2zFYP3b0xlGNgQ',
    'CgACAgQAAxkBAAICSGcrsYv8-w0O6f7h0QqDFSyBuWunAAL6AgACNggMU5kkgeDxVYZxNgQ'
];

module.exports = {startGifs, cancelGifs};
