const teamNames = [
    'Борцы за победу',
    'Ловкие парни',
    'Неуловимые пираты',
    'Football Muscle',
    'Red Bull',
    'Голодные звери',
    'Жаждущие крови',
    'Черная банда',
    'Безумные волки',
    'Дикие львы',
    'Монстры с клыками',
    'Древние зомби',
    'Сверхточная ракета',
    'Беглые преступники',
    'Football Dragon',
    'Best Winners',
    'Сверхзвуковые ракеты',
    'Crazy Guys',
    'Super Boys',
    'Football Tigers',
    'Черепашки Ниндзя',
    'Синяя молния',
    'Летающие воины',
    'Безумные змеи',
    'Серые львы',
    'Top Guns',
    'Gold Ball',
    'Flying tornado',
    'Big lightning',
    'Boys Territory',
    'Win in blood',
    'Fast torpedo',
    'Evil Bears',
    'Wild lions',
    'Foot referee',
    'Black Holes',
    'Полярные медведи',
    'Черные принцы',
    'Красные драконы',
    'Черные буйволы',
    'Evil monsters',
    'Золотая звезда',
    'Команда-А',
    'Недосягаемые монстры',
    'Стальной меч',
];

module.exports = teamNames;
